import type { FullEndpoint } from "./parser/types.js";
import type { WorkflowDefinition } from "./types.js";

export function generateRestClientCode(): string {
  return `/**
 * Rocket.Chat API Client
 * Generated by rc-mcp-generator
 *
 * Centralizes HTTP communication with the Rocket.Chat server.
 * Auth priority:
 *   1. Pre-existing tokens (ROCKETCHAT_AUTH_TOKEN + ROCKETCHAT_USER_ID) — bot credentials, no login needed
 *   2. Username/password (ROCKETCHAT_USER + ROCKETCHAT_PASSWORD) — admin credentials, auto-login
 *   3. Unconfigured mode — server runs but tools prompt for setup
 *
 * On first run with admin credentials, the auto-config creates a dedicated
 * bot user and writes its token to .env. Subsequent runs use the token directly.
 *
 * All tool handlers use client.request() instead of raw fetch.
 */

import { createHash } from "node:crypto";

// ─── Configuration ──────────────────────────────────────────────────────────

const config = {
  baseUrl: process.env.ROCKETCHAT_URL || "http://localhost:3000",
  authToken: process.env.ROCKETCHAT_AUTH_TOKEN || "",
  userId: process.env.ROCKETCHAT_USER_ID || "",
};

// ─── Types ──────────────────────────────────────────────────────────────────

export type ToolResult = {
  content: { type: string; text: string }[];
  isError?: boolean;
};

// ─── 2FA Helper ─────────────────────────────────────────────────────────────

/** SHA-256 hash of a password — used as x-2fa-code with x-2fa-method: password */
export function get2faHash(password: string): string {
  return createHash("sha256").update(password).digest("hex");
}

// ─── Auth ───────────────────────────────────────────────────────────────────

let initialized = false;

/**
 * Authenticate with Rocket.Chat at startup.
 * Priority:
 *   1. ROCKETCHAT_AUTH_TOKEN + ROCKETCHAT_USER_ID → use directly (bot token)
 *   2. ROCKETCHAT_USER + ROCKETCHAT_PASSWORD → auto-login (admin, for initial setup)
 *   3. Neither → unconfigured mode
 */
export let authConfigured = false;

export async function initAuth(): Promise<void> {
  if (initialized) return;
  initialized = true;

  // Mode 1: pre-existing tokens (bot credentials — takes priority)
  if (config.authToken && config.userId) {
    authConfigured = true;
    console.error("Using pre-existing auth tokens.");
    return;
  }

  // Mode 2: username/password → auto-login (admin, for initial bot setup)
  const user = process.env.ROCKETCHAT_USER || "";
  const password = process.env.ROCKETCHAT_PASSWORD || "";

  if (user && password) {
    try {
      const res = await fetch(\`\${config.baseUrl}/api/v1/login\`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ user, password }),
      });
      const data = await res.json();
      if (!res.ok || !data.data?.authToken) {
        console.error("Login failed:", JSON.stringify(data));
        console.error("Server starting in unconfigured mode. Edit .env with your credentials and restart.");
        return;
      }
      config.authToken = data.data.authToken;
      config.userId = data.data.userId;
      authConfigured = true;
      console.error(\`Authenticated as \${user}\`);
    } catch (err) {
      console.error(\`Could not connect to \${config.baseUrl}: \${err instanceof Error ? err.message : err}\`);
      console.error("Server starting in unconfigured mode. Edit .env with your credentials and restart.");
    }
    return;
  }

  // No credentials at all — start in unconfigured mode
  console.error("No Rocket.Chat credentials found. Server starting in unconfigured mode.");
  console.error("Copy .env.example to .env and fill in your credentials, then restart.");
}

// ─── Client ─────────────────────────────────────────────────────────────────

class RocketChatClient {
  /** Update credentials after a successful login call */
  setAuth(token: string, userId: string) {
    config.authToken = token;
    config.userId = userId;
  }

  async request(
    method: string,
    path: string,
    options: { auth?: boolean; body?: unknown; headers?: Record<string, string> } = {},
  ): Promise<ToolResult> {
    const url = \`\${config.baseUrl}\${path}\`;
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...options.headers,
    };
    if (options.auth) {
      headers["X-Auth-Token"] = config.authToken;
      headers["X-User-Id"] = config.userId;
    }

    const fetchOpts: RequestInit = { method, headers };
    if (options.body !== undefined) {
      fetchOpts.body = JSON.stringify(options.body);
    }

    const res = await fetch(url, fetchOpts);
    const data = await res.json();

    if (!res.ok) {
      return {
        content: [{ type: "text", text: \`API error \${res.status}: \${JSON.stringify(data)}\` }],
        isError: true,
      };
    }
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
}

export const client = new RocketChatClient();
`;
}

export function generateMcpServerPackageJson(serverName: string): string {
  const pkg = {
    name: serverName,
    version: "1.0.0",
    type: "module",
    scripts: {
      start: "node --env-file-if-exists=.env --import tsx src/server.ts",
      build: "tsc",
      "start:built": "node dist/server.js",
      test: "tsx --test src/tests/*.test.ts",
    },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.27.1",
      zod: "^3.25.76",
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      tsx: "^4.21.0",
      typescript: "^5.9.3",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

export function generateMcpServerTsConfig(): string {
  const config = {
    compilerOptions: {
      target: "ES2022",
      module: "Node16",
      moduleResolution: "Node16",
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
    },
    include: ["src"],
  };
  return JSON.stringify(config, null, 2) + "\n";
}

export function generateMcpServerEnvExample(options?: {
  bridged?: boolean;
  usesSampling?: boolean;
}): string {
  let env = `# Rocket.Chat connection settings
ROCKETCHAT_URL=http://localhost:3000

# Admin credentials (used for initial bot setup on first run)
ROCKETCHAT_USER=your-admin-username
ROCKETCHAT_PASSWORD=your-admin-password

# Bot credentials (auto-generated on first run — takes priority when set)
# ROCKETCHAT_AUTH_TOKEN=auto-generated-on-first-run
# ROCKETCHAT_USER_ID=auto-generated-on-first-run
`;

  if (options?.usesSampling) {
    env += `
# AI Sampling — the workflow engine uses these for LLM judgment steps.
# Primary: Gemini CLI headless mode (1,000 requests/day with Google account).
#   Install: npm install -g @google/gemini-cli
#   Auth:    Run \`gemini\` once and sign in with Google.
# Fallback: Direct API key (500 requests/day free tier).
#   Get one at https://aistudio.google.com/apikey
# GEMINI_API_KEY=your-api-key-here
`;
  }

  if (options?.bridged) {
    env += `
# HTTP bridge port for RC App connections
MCP_HTTP_PORT=3001
`;
  }

  return env;
}

export function generateMcpServerReadme(
  serverName: string,
  endpoints: FullEndpoint[],
): string {
  const date = new Date().toISOString().split("T")[0];

  const endpointRows = endpoints
    .map((ep) => {
      const summary = ep.summary || ep.description || "—";
      return `| \`${ep.operationId}\` | \`${ep.method.toUpperCase()}\` | \`${ep.path}\` | ${summary} |`;
    })
    .join("\n");

  return `# ${serverName}

A workflow-based [MCP](https://modelcontextprotocol.io/) server for Rocket.Chat, generated by **rc-mcp-generator**.

- **Workflow tools** — each tool chains multiple API calls, AI reasoning, and user confirmation
- **stdio transport** — works with any MCP-compatible client
- **Dual auth** — username/password auto-login or pre-existing tokens

> Generated on ${date}

## Quick Start

\`\`\`bash
npm install
cp .env.example .env
# Edit .env with your Rocket.Chat credentials
npm start
\`\`\`

## Authentication

Two modes are supported (configure in \`.env\`):

**Mode 1 — Username / Password (recommended)**
\`\`\`env
ROCKETCHAT_URL=http://localhost:3000
ROCKETCHAT_USER=your-username
ROCKETCHAT_PASSWORD=your-password
\`\`\`
The server calls \`/api/v1/login\` at startup and stores the token in memory.

**Mode 2 — Pre-existing Tokens**
\`\`\`env
ROCKETCHAT_URL=http://localhost:3000
ROCKETCHAT_AUTH_TOKEN=your-token
ROCKETCHAT_USER_ID=your-user-id
\`\`\`

## Project Structure

\`\`\`
${serverName}/
├── src/
│   ├── server.ts          # Entry point — wires workflow tools + stdio transport
│   ├── rc-client.ts       # Rocket.Chat HTTP client (auth, errors)
│   ├── tools/             # Workflow tool files (one per workflow)
│   └── tests/
│       └── setup.ts       # Shared mock-fetch infrastructure
├── .env.example
├── package.json
├── tsconfig.json
└── README.md
\`\`\`

## API Endpoints Used

These RC REST API endpoints are called internally by the workflow tools:

| Endpoint | Method | Path | Summary |
|----------|--------|------|---------|
${endpointRows}

## Testing

\`\`\`bash
npm test
\`\`\`

## Connect to Your MCP Client

This server uses **stdio transport** — it works with any MCP-compatible client.

### Gemini CLI (auto-linked on generation)

\`\`\`jsonc
// ~/.gemini/settings.json
{
  "mcpServers": {
    "${serverName}": {
      "command": "node",
      "args": ["--env-file-if-exists=.env", "--import", "tsx", "src/server.ts"],
      "cwd": "/absolute/path/to/${serverName}/mcp-server"
    }
  }
}
\`\`\`

### Claude Desktop

\`\`\`jsonc
// ~/Library/Application Support/Claude/claude_desktop_config.json (macOS)
// %APPDATA%\\Claude\\claude_desktop_config.json (Windows)
{
  "mcpServers": {
    "${serverName}": {
      "command": "node",
      "args": ["--env-file-if-exists=.env", "--import", "tsx", "src/server.ts"],
      "cwd": "/absolute/path/to/${serverName}/mcp-server"
    }
  }
}
\`\`\`

### VS Code

\`\`\`jsonc
// .vscode/mcp.json in your workspace
{
  "servers": {
    "${serverName}": {
      "command": "node",
      "args": ["--env-file-if-exists=.env", "--import", "tsx", "src/server.ts"],
      "cwd": "/absolute/path/to/${serverName}/mcp-server"
    }
  }
}
\`\`\`

### Cursor

\`\`\`jsonc
// ~/.cursor/mcp.json
{
  "mcpServers": {
    "${serverName}": {
      "command": "node",
      "args": ["--env-file-if-exists=.env", "--import", "tsx", "src/server.ts"],
      "cwd": "/absolute/path/to/${serverName}/mcp-server"
    }
  }
}
\`\`\`

> **Note:** Replace \`/absolute/path/to/\` with the actual path where this project lives.

## Scripts

| Script | Description |
|--------|-------------|
| \`npm start\` | Run with tsx (loads \`.env\`) |
| \`npm run build\` | Compile TypeScript to \`dist/\` |
| \`npm run start:built\` | Run compiled JS |
| \`npm test\` | Run all tests |

---

*Generated by [rc-mcp-generator](https://github.com/RocketChat/gsoc-mcp-server-generator)*
`;
}

export function generateTestSetupCode(workflowNames: string[]): string {
  const toolImports = workflowNames
    .map(
      (name, i) => `import { tool as wfTool${i} } from "../tools/${name}.js";`,
    )
    .join("\n");
  const toolArray = workflowNames.map((_, i) => `wfTool${i}`).join(", ");

  return `/**
 * Shared test setup — mock fetch infrastructure
 * Generated by rc-mcp-generator
 *
 * Provides a mocked fetch that captures request details for assertion.
 * All test files import from here for consistent setup.
 */

import { mock } from "node:test";
${toolImports}

interface ToolDefinition {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  handler: (args: Record<string, unknown>) => Promise<{ content: { type: string; text: string }[]; isError?: boolean }>;
}

/** Shared test state */
export const ctx: {
  tools: ToolDefinition[];
  lastFetchUrl: string;
  lastFetchOptions: RequestInit;
  mockFetch: ReturnType<typeof mock.fn>;
} = {
  tools: [${toolArray}],
  lastFetchUrl: "",
  lastFetchOptions: {},
  mockFetch: mock.fn(async (url: string | URL | Request, init?: RequestInit) => {
    ctx.lastFetchUrl = String(url);
    ctx.lastFetchOptions = init || {};
    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }),
};

let initialized = false;

/** Call in before() — sets env vars, mocks fetch */
export async function init(): Promise<void> {
  if (initialized) return;
  initialized = true;
  process.env.ROCKETCHAT_URL = "http://localhost:3000";
  process.env.ROCKETCHAT_AUTH_TOKEN = "test-token";
  process.env.ROCKETCHAT_USER_ID = "test-user-id";
  (globalThis as any).fetch = ctx.mockFetch;
}

/** Call in beforeEach() — resets captured request state */
export function reset(): void {
  ctx.lastFetchUrl = "";
  ctx.lastFetchOptions = {};
  ctx.mockFetch.mock.resetCalls();
}
`;
}

export function generateToolTestCode(workflow: WorkflowDefinition): string {
  const stepTypes = new Set(workflow.steps.map((s) => s.config.type));
  const hasApiCall = stepTypes.has("api_call");
  const hasTransform = stepTypes.has("transform");
  const hasSampling = stepTypes.has("sampling");
  const hasConditional = stepTypes.has("conditional");

  const firstApiCall = workflow.steps.find((s) => s.config.type === "api_call");
  const firstTransform = workflow.steps.find(
    (s) => s.config.type === "transform",
  );
  const firstSampling = workflow.steps.find(
    (s) => s.config.type === "sampling",
  );
  const firstConditional = workflow.steps.find(
    (s) => s.config.type === "conditional",
  );

  const paramProps = (workflow.params as any)?.properties || {};
  const sampleArgs: Record<string, unknown> = {};
  for (const [key, schema] of Object.entries(paramProps)) {
    const s = schema as any;
    if (s.default !== undefined) sampleArgs[key] = s.default;
    else if (s.type === "string") sampleArgs[key] = `test-${key}`;
    else if (s.type === "number" || s.type === "integer") sampleArgs[key] = 1;
    else if (s.type === "boolean") sampleArgs[key] = true;
    else sampleArgs[key] = `test-${key}`;
  }

  let code = `/**
 * Tests for workflow: ${workflow.name}
 * Generated by rc-mcp-generator
 *
 * Step types tested: ${[...stepTypes].join(", ")}
 */

import { describe, it, before, beforeEach } from "node:test";
import assert from "node:assert/strict";
import { init, reset, ctx } from "./setup.js";
import { tool } from "../tools/${workflow.name}.js";
`;

  if (hasTransform || hasConditional) {
    code += `import { resolveTemplate } from "../engine/workflow-engine.js";\n`;
  }

  code += `
describe("${workflow.name}", () => {
  before(async () => {
    await init();
  });

  beforeEach(() => {
    reset();
  });

  it("has correct tool metadata", () => {
    assert.equal(tool.name, "${workflow.name}");
    assert.ok(tool.description.length > 0, "description should not be empty");
    assert.ok(tool.handler, "handler should be defined");
  });
`;

  if (hasApiCall && firstApiCall) {
    const cfg = firstApiCall.config as any;
    code += `
  describe("step: ${firstApiCall.id} (api_call)", () => {
    it("calls the correct API endpoint", async () => {
      // Mock a successful RC API response
      ctx.mockFetch.mock.mockImplementationOnce(async (url: string | URL | Request, init?: RequestInit) => {
        ctx.lastFetchUrl = String(url);
        ctx.lastFetchOptions = init || {};
        return new Response(JSON.stringify({ success: true }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        });
      }, 0);

      const result = await tool.handler(${JSON.stringify(sampleArgs)});
      const body = JSON.parse(result.content[0].text);

      // The workflow should have attempted at least one API call
      assert.ok(ctx.lastFetchUrl.length > 0, "should have made a fetch call");
      assert.ok(
        ctx.lastFetchUrl.includes("/api/"),
        "should call an RC API endpoint",
      );
    });
  });
`;
  }

  if (hasTransform && firstTransform) {
    const cfg = firstTransform.config as any;
    const exprPreview = (cfg.expression || "null").substring(0, 60);
    code += `
  describe("step: ${firstTransform.id} (transform)", () => {
    it("resolves template expressions correctly", () => {
      const result = resolveTemplate(
        "{{params.test}}",
        { test: "hello" },
        {},
      );
      assert.equal(result, "hello");
    });

    it("handles missing template values gracefully", () => {
      const result = resolveTemplate(
        "{{params.missing}}",
        {},
        {},
      );
      assert.equal(result, "undefined");
    });
  });
`;
  }

  if (hasSampling && firstSampling) {
    code += `
  describe("step: ${firstSampling.id} (sampling)", () => {
    it("completes with mocked Gemini API", async () => {
      // Mock the Gemini API response
      process.env.GEMINI_API_KEY = "test-key";
      ctx.mockFetch.mock.mockImplementation(async (url: string | URL | Request, init?: RequestInit) => {
        const urlStr = String(url);
        ctx.lastFetchUrl = urlStr;
        ctx.lastFetchOptions = init || {};

        if (urlStr.includes("generativelanguage.googleapis.com")) {
          return new Response(
            JSON.stringify({
              candidates: [
                { content: { parts: [{ text: "AI response for testing" }] } },
              ],
            }),
            { status: 200, headers: { "Content-Type": "application/json" } },
          );
        }

        return new Response(JSON.stringify({ success: true }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        });
      });

      const result = await tool.handler(${JSON.stringify(sampleArgs)});
      assert.ok(!result.isError, "should not be an error: " + result.content[0]?.text);
      delete process.env.GEMINI_API_KEY;
    });
  });
`;
  }

  if (hasConditional && firstConditional) {
    const cfg = firstConditional.config as any;
    code += `
  describe("step: ${firstConditional.id} (conditional)", () => {
    it("template resolution works for condition expressions", () => {
      // Verify template resolution handles boolean-like expressions
      const result = resolveTemplate(
        "{{params.flag ? 'yes' : 'no'}}",
        { flag: true },
        {},
      );
      assert.equal(result, "yes");

      const result2 = resolveTemplate(
        "{{params.flag ? 'yes' : 'no'}}",
        { flag: false },
        {},
      );
      assert.equal(result2, "no");
    });
  });
`;
  }

  code += `
  describe("full workflow", () => {
    it("runs without throwing", async () => {`;

  if (hasSampling) {
    code += `
      // Setup Gemini mock for sampling steps
      process.env.GEMINI_API_KEY = "test-key";
      ctx.mockFetch.mock.mockImplementation(async (url: string | URL | Request, init?: RequestInit) => {
        const urlStr = String(url);
        ctx.lastFetchUrl = urlStr;
        ctx.lastFetchOptions = init || {};

        if (urlStr.includes("generativelanguage.googleapis.com")) {
          return new Response(
            JSON.stringify({
              candidates: [
                { content: { parts: [{ text: "test response" }] } },
              ],
            }),
            { status: 200, headers: { "Content-Type": "application/json" } },
          );
        }

        return new Response(JSON.stringify({ success: true }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        });
      });`;
  }

  code += `

      const result = await tool.handler(${JSON.stringify(sampleArgs)});
      assert.ok(result.content, "should return content");
      assert.ok(result.content.length > 0, "should return at least one content item");

      const body = JSON.parse(result.content[0].text);
      assert.ok(body.completedSteps, "should have completedSteps");`;

  if (hasSampling) {
    code += `
      delete process.env.GEMINI_API_KEY;`;
  }

  code += `
    });
  });
});
`;

  return code;
}
