import type {
  PersistenceConfig,
  WorkflowDefinition,
  WorkflowStep,
} from "../mcp-server/types.js";
import type { AppCapability } from "./types.js";
import { toPascalCase } from "../utils.js";

function esc(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${")
    .replace(/'/g, "\\'");
}

function toCamelCase(s: string): string {
  const pascal = toPascalCase(s);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

export function generateAppManifestCode(
  appName: string,
  description: string,
  existingId?: string,
): string {
  const id = existingId ?? crypto.randomUUID();

  const className = toPascalCase(appName) + "App";

  return JSON.stringify(
    {
      id,
      version: "0.0.1",
      requiredApiVersion: "^1.4.0",
      iconFile: "icon.png",
      author: {
        name: "RC MCP Generator",
        homepage: "https://github.com/RocketChat",
        support: "https://github.com/RocketChat",
      },
      name: appName,
      nameSlug: appName
        .toLowerCase()
        .replace(/[^a-z-]+/g, "-")
        .replace(/^-+|-+$/g, ""),
      classFile: `${className}.ts`,
      description,
    },
    null,
    2,
  );
}

export interface AppGenOptions {
  appName: string;
  description: string;
  commands: SlashCommandDef[];
  messageHandlers: boolean;
  webhookEndpoints: WebhookEndpointDef[];
  workflows: WorkflowDefinition[];
  bridged?: boolean;
}

export interface SlashCommandDef {
  command: string;
  description: string;
  workflowName?: string;
}

export interface WebhookEndpointDef {
  path: string;
  description: string;
  methods: ("get" | "post")[];
}

export function generateAppClassCode(options: AppGenOptions): string {
  const className = toPascalCase(options.appName) + "App";
  const imports: string[] = [
    `import {\n    IAppAccessors,\n    IConfigurationExtend,\n    ILogger,\n} from '@rocket.chat/apps-engine/definition/accessors';`,
    `import { App } from '@rocket.chat/apps-engine/definition/App';`,
    `import { IAppInfo } from '@rocket.chat/apps-engine/definition/metadata';`,
    `import { settings } from './settings/settings';`,
  ];

  const extendConfigLines: string[] = [];
  const implementsList: string[] = [];

  extendConfigLines.push(
    `        await Promise.all(settings.map((s) => configuration.settings.provideSetting(s)));`,
  );

  if (options.commands.length > 0) {
    for (const cmd of options.commands) {
      const cmdClassName = toPascalCase(cmd.command) + "Command";
      imports.push(
        `import { ${cmdClassName} } from './commands/${cmd.command}';`,
      );
      extendConfigLines.push(
        `        configuration.slashCommands.provideSlashCommand(new ${cmdClassName}(this));`,
      );
    }
  }

  if (options.messageHandlers) {
    imports.push(
      `import { IPostMessageSent } from '@rocket.chat/apps-engine/definition/messages';`,
    );
    imports.push(
      `import { IMessage } from '@rocket.chat/apps-engine/definition/messages';`,
    );
    imports.push(
      `import { IHttp, IModify, IPersistence, IRead } from '@rocket.chat/apps-engine/definition/accessors';`,
    );
    imports.push(
      `import { PostMessageSentHandler } from './handlers/PostMessageSentHandler';`,
    );
    implementsList.push("IPostMessageSent");
  }

  if (options.webhookEndpoints.length > 0) {
    imports.push(
      `import { ApiSecurity, ApiVisibility } from '@rocket.chat/apps-engine/definition/api';`,
    );
    for (const ep of options.webhookEndpoints) {
      const epClassName = toPascalCase(ep.path) + "Endpoint";
      imports.push(`import { ${epClassName} } from './endpoints/${ep.path}';`);
      extendConfigLines.push(
        `        await configuration.api.provideApi({`,
        `            visibility: ApiVisibility.PUBLIC,`,
        `            security: ApiSecurity.UNSECURE,`,
        `            endpoints: [new ${epClassName}(this)],`,
        `        });`,
      );
    }
  }

  const implementsStr =
    implementsList.length > 0 ? ` implements ${implementsList.join(", ")}` : "";

  let messageHandler = "";
  if (options.messageHandlers) {
    messageHandler = `
    public async executePostMessageSent(
        message: IMessage,
        read: IRead,
        http: IHttp,
        persistence: IPersistence,
        modify: IModify,
    ): Promise<void> {
        const handler = new PostMessageSentHandler(this, message, read, http, persistence, modify);
        await handler.run();
    }
`;
  }

  return `/**
 * ${options.appName} — Rocket.Chat App
 * ${esc(options.description)}
 *
 * Generated by rc-mcp-generator (RC App mode)
 * Deploy: rc-apps deploy --url <server_url> -u <user> -p <password>
 */

${imports.join("\n")}

export class ${className} extends App${implementsStr} {
    constructor(info: IAppInfo, logger: ILogger, accessors: IAppAccessors) {
        super(info, logger, accessors);
        logger.debug('${esc(options.appName)} initialized');
    }

    public async extendConfiguration(configuration: IConfigurationExtend): Promise<void> {
${extendConfigLines.join("\n")}
    }
${messageHandler}}
`;
}

export function generateSlashCommandCode(
  cmd: SlashCommandDef,
  workflow?: WorkflowDefinition,
  bridged?: boolean,
): string {
  const className = toPascalCase(cmd.command) + "Command";

  let handlerBody: string;
  if (workflow && bridged) {
    handlerBody = generateBridgedCommandBody(workflow);
  } else if (workflow) {
    handlerBody = generateWorkflowCommandBody(workflow);
  } else {
    handlerBody = `
        const msg = modify.getCreator().startMessage()
            .setText('Command /${esc(cmd.command)} executed successfully.')
            .setRoom(context.getRoom());
        await modify.getCreator().finish(msg);`;
  }

  const extraImports = bridged
    ? `import { McpBridge } from '../bridge/mcp-bridge';\n`
    : "";

  return `/**
 * Slash Command: /${cmd.command}
 * ${esc(cmd.description)}
 *
 * Generated by rc-mcp-generator (RC App mode)
 */

import {
    IHttp,
    IModify,
    IPersistence,
    IRead,
} from '@rocket.chat/apps-engine/definition/accessors';
import {
    ISlashCommand,
    SlashCommandContext,
} from '@rocket.chat/apps-engine/definition/slashcommands';
import { App } from '@rocket.chat/apps-engine/definition/App';
${extraImports}

export class ${className} implements ISlashCommand {
    public command = '${esc(cmd.command)}';
    public i18nParamsExample = '';
    public i18nDescription = '${esc(cmd.description)}';
    public providesPreview = false;

    private readonly app: App;

    constructor(app: App) {
        this.app = app;
    }

    public async executor(
        context: SlashCommandContext,
        read: IRead,
        modify: IModify,
        http: IHttp,
        persis: IPersistence,
    ): Promise<void> {
        const logger = this.app.getLogger();
        const args = context.getArguments();
        const room = context.getRoom();
        const sender = context.getSender();

        logger.debug(\`/${esc(cmd.command)} invoked by \${sender.username} with args: \${args.join(' ')}\`);

        try {
${handlerBody}
        } catch (error) {
            logger.error(\`/${esc(cmd.command)} failed:\`, error);
            const errMsg = modify.getCreator().startMessage()
                .setText(\`Error executing /${esc(cmd.command)}: \${error instanceof Error ? error.message : String(error)}\`)
                .setRoom(room);
            await modify.getCreator().finish(errMsg);
        }
    }
}
`;
}

function generateWorkflowCommandBody(workflow: WorkflowDefinition): string {
  const lines: string[] = [];

  lines.push(`            // Workflow: ${esc(workflow.name)}`);
  lines.push(
    `            // Steps: ${workflow.steps.map((s) => s.id).join(" → ")}`,
  );
  lines.push(``);

  lines.push(
    `            const statusMsg = modify.getCreator().startMessage()`,
  );
  lines.push(
    `                .setText('⏳ Running workflow: ${esc(workflow.name)}...')`,
  );
  lines.push(`                .setRoom(room);`);
  lines.push(`            await modify.getCreator().finish(statusMsg);`);
  lines.push(``);
  lines.push(`            const stepResults: Record<string, any> = {};`);
  lines.push(`            const completedSteps: string[] = [];`);
  lines.push(``);
  lines.push(`            // Parse slash command arguments`);
  lines.push(`            const rawArgs = args.join(' ');`);
  lines.push(`            const params: Record<string, any> = {`);
  lines.push(`                roomId: room.id,`);
  lines.push(`                senderId: sender.id,`);
  lines.push(`                senderUsername: sender.username,`);
  lines.push(`                query: rawArgs,`);
  lines.push(`            };`);
  lines.push(`            for (const arg of args) {`);
  lines.push(`                const [key, ...rest] = arg.split('=');`);
  lines.push(
    `                if (rest.length > 0) params[key] = rest.join('=');`,
  );
  lines.push(`            }`);

  for (const step of workflow.steps) {
    lines.push(``);
    lines.push(`            // Step: ${esc(step.label)} (${step.config.type})`);
    lines.push(
      `            logger.debug('[${esc(step.id)}] ${esc(step.label)}...');`,
    );

    switch (step.config.type) {
      case "api_call": {
        const cfg = step.config;
        const methodMatch = cfg.operationId.match(/^(get|post|put|delete)-/);
        const httpMethod = methodMatch ? methodMatch[1] : "get";
        const apiPath = cfg.operationId
          .replace(/^(get|post|put|delete)-api-v1-/, "")
          .replace(/-/g, ".");
        lines.push(
          `            const ${step.id}_response = await http.${esc(httpMethod)}(\`\${await read.getEnvironmentReader().getServerSettings().getValueById('Site_Url')}/api/v1/${esc(apiPath)}\`, {`,
        );
        lines.push(`                headers: {`);
        lines.push(`                    'Content-Type': 'application/json',`);
        lines.push(`                },`);
        lines.push(`            });`);
        lines.push(
          `            stepResults['${esc(step.id)}'] = { result: ${step.id}_response?.data, status: 'success' };`,
        );
        lines.push(`            completedSteps.push('${esc(step.id)}');`);
        break;
      }
      case "transform": {
        const cfg = step.config;
        lines.push(
          `            const ${step.id}_result = ((steps: any, p: any) => (${cfg.expression}))(stepResults, params);`,
        );
        lines.push(
          `            stepResults['${esc(step.id)}'] = { result: ${step.id}_result, status: 'success' };`,
        );
        lines.push(`            completedSteps.push('${esc(step.id)}');`);
        break;
      }
      case "sampling": {
        lines.push(
          `            // NOTE: Sampling (LLM analysis) is not natively available in RC Apps.`,
        );
        lines.push(
          `            // To use AI, integrate with an external LLM API via http.post().`,
        );
        lines.push(
          `            stepResults['${esc(step.id)}'] = { result: 'LLM analysis placeholder — integrate external AI API', status: 'skipped' };`,
        );
        lines.push(`            completedSteps.push('${esc(step.id)}');`);
        break;
      }
      case "elicitation": {
        lines.push(
          `            // NOTE: Elicitation maps to user interaction via messages in RC Apps.`,
        );
        lines.push(
          `            // For structured input, use Apps-Engine UI Kit (modals/action buttons).`,
        );
        lines.push(
          `            stepResults['${esc(step.id)}'] = { result: 'User confirmation placeholder — use UI Kit for modals', status: 'skipped' };`,
        );
        lines.push(`            completedSteps.push('${esc(step.id)}');`);
        break;
      }
      case "conditional": {
        const cfg = step.config;
        lines.push(
          `            const ${step.id}_condition = ((steps: any, p: any) => !!(${cfg.condition}))(stepResults, params);`,
        );
        lines.push(
          `            stepResults['${esc(step.id)}'] = { result: ${step.id}_condition, status: 'success' };`,
        );
        lines.push(`            completedSteps.push('${esc(step.id)}');`);
        break;
      }
    }
  }

  lines.push(``);
  lines.push(`            // Send results`);
  lines.push(`            const resultText = [`);
  lines.push(
    `                '✅ Workflow "${esc(workflow.name)}" completed',`,
  );
  lines.push(
    `                \`Steps completed: \${completedSteps.length}/${workflow.steps.length}\`,`,
  );
  lines.push(`                '',`);
  lines.push(
    `                ...completedSteps.map(s => \`  ✓ \${s}: \${JSON.stringify(stepResults[s]?.result ?? 'done').slice(0, 200)}\`),`,
  );
  lines.push(`            ].join('\\n');`);
  lines.push(``);
  lines.push(
    `            const resultMsg = modify.getCreator().startMessage()`,
  );
  lines.push(`                .setText(resultText)`);
  lines.push(`                .setRoom(room);`);
  lines.push(`            await modify.getCreator().finish(resultMsg);`);

  return lines.join("\n");
}

function generateBridgedCommandBody(workflow: WorkflowDefinition): string {
  const lines: string[] = [];

  const EVENT_DOMAIN_PARAMS = new Set(["message", "room", "context"]);
  const schemaProps = (workflow.params as any)?.properties ?? {};
  const missingDomainParams = Object.keys(schemaProps).filter((k) =>
    EVENT_DOMAIN_PARAMS.has(k),
  );

  if (missingDomainParams.length > 0) {
    const paramList = missingDomainParams.map((p) => `\`${p}\``).join(", ");
    lines.push(
      `            // This workflow requires event data (${missingDomainParams.join(", ")}) that slash commands cannot provide.`,
    );
    lines.push(
      `            const infoMsg = modify.getCreator().startMessage()`,
    );
    lines.push(
      `                .setText('This workflow is event-driven and requires ${paramList} data that is only available when triggered by a Rocket.Chat event (e.g. a new message). It cannot be invoked via a slash command.')`,
    );
    lines.push(`                .setRoom(room);`);
    lines.push(`            await modify.getCreator().finish(infoMsg);`);
    return lines.join("\n");
  }

  lines.push(
    `            // Workflow: ${esc(workflow.name)} (delegated to MCP Server)`,
  );
  lines.push(``);
  lines.push(
    `            const statusMsg = modify.getCreator().startMessage()`,
  );
  lines.push(
    `                .setText('⏳ Running workflow: ${esc(workflow.name)}...')`,
  );
  lines.push(`                .setRoom(room);`);
  lines.push(`            await modify.getCreator().finish(statusMsg);`);
  lines.push(``);
  lines.push(`            // Parse slash command arguments`);
  lines.push(`            const rawArgs = args.join(' ');`);
  lines.push(`            const kvParams: Record<string, string> = {};`);
  lines.push(`            for (const arg of args) {`);
  lines.push(`                const [key, ...rest] = arg.split('=');`);
  lines.push(
    `                if (rest.length > 0) kvParams[key] = rest.join('=');`,
  );
  lines.push(`            }`);
  lines.push(``);
  lines.push(`            // Delegate to MCP Server via bridge`);
  lines.push(`            const bridge = new McpBridge(http, read);`);
  lines.push(
    `            const result = await bridge.callTool('${esc(workflow.name)}', {`,
  );
  lines.push(`                roomId: room.id,`);
  lines.push(`                senderId: sender.id,`);
  lines.push(`                senderUsername: sender.username,`);
  lines.push(`                query: rawArgs,`);
  lines.push(`                ...kvParams,`);
  lines.push(`            });`);
  lines.push(``);
  lines.push(
    `            if (result.status === 'success' && result.content) {`,
  );
  lines.push(
    `                const resultMsg = modify.getCreator().startMessage()`,
  );
  lines.push(`                    .setText(result.content)`);
  lines.push(`                    .setRoom(room);`);
  lines.push(`                await modify.getCreator().finish(resultMsg);`);
  lines.push(`            } else {`);
  lines.push(
    `                const errMsg = modify.getCreator().startMessage()`,
  );
  lines.push(
    `                    .setText(\`Workflow failed: \${result.content || 'Unknown error'}\`)`,
  );
  lines.push(`                    .setRoom(room);`);
  lines.push(`                await modify.getCreator().finish(errMsg);`);
  lines.push(`            }`);

  return lines.join("\n");
}

export function generateWebhookEndpointCode(ep: WebhookEndpointDef): string {
  const className = toPascalCase(ep.path) + "Endpoint";
  const methods: string[] = [];

  for (const method of ep.methods) {
    methods.push(`
    public async ${method}(
        request: IApiRequest,
        endpoint: IApiEndpointInfo,
        read: IRead,
        modify: IModify,
    ): Promise<IApiResponse> {
        const logger = this.app.getLogger();
        logger.debug('${method.toUpperCase()} /${esc(ep.path)} received:', JSON.stringify(request.content));

        // Process the incoming webhook data
        const data = request.content;

        // Example: Post a message to #general with the webhook data
        const room = await read.getRoomReader().getByName('general');
        if (room) {
            const body = typeof data === 'object'
                ? Object.entries(data).map(([k, v]) => \`\${k}: \${v}\`).join('\\n')
                : String(data);

            const msg = modify.getCreator().startMessage()
                .setText(\`📥 Webhook received on /${esc(ep.path)}:\\n\${body}\`)
                .setRoom(room);
            await modify.getCreator().finish(msg);
        }

        return this.success(JSON.stringify({ status: 'ok' }));
    }`);
  }

  return `/**
 * Webhook Endpoint: /${ep.path}
 * ${esc(ep.description)}
 *
 * Generated by rc-mcp-generator (RC App mode)
 */

import {
    IModify,
    IRead,
} from '@rocket.chat/apps-engine/definition/accessors';
import {
    ApiEndpoint,
    IApiEndpointInfo,
    IApiRequest,
    IApiResponse,
} from '@rocket.chat/apps-engine/definition/api';

export class ${className} extends ApiEndpoint {
    public path = '${esc(ep.path)}';
${methods.join("\n")}
}
`;
}

export function generateDynamicAppClassCode(
  options: AppGenOptions,
  capabilities: AppCapability[],
): string {
  const className = toPascalCase(options.appName) + "App";

  const imports: string[] = [
    `import {\n    IAppAccessors,\n    IConfigurationExtend,\n    ILogger,\n} from '@rocket.chat/apps-engine/definition/accessors';`,
    `import { App } from '@rocket.chat/apps-engine/definition/App';`,
    `import { IAppInfo } from '@rocket.chat/apps-engine/definition/metadata';`,
    `import { settings } from './settings/settings';`,
  ];

  const extendConfigLines: string[] = [];
  const implementsList: string[] = [];
  const methodBlocks: string[] = [];

  extendConfigLines.push(
    `        await Promise.all(settings.map((s) => configuration.settings.provideSetting(s)));`,
  );

  if (options.commands.length > 0) {
    for (const cmd of options.commands) {
      const cmdClassName = toPascalCase(cmd.command) + "Command";
      imports.push(
        `import { ${cmdClassName} } from './commands/${cmd.command}';`,
      );
      extendConfigLines.push(
        `        configuration.slashCommands.provideSlashCommand(new ${cmdClassName}(this));`,
      );
    }
  }

  if (options.webhookEndpoints.length > 0) {
    imports.push(
      `import { ApiSecurity, ApiVisibility } from '@rocket.chat/apps-engine/definition/api';`,
    );
    for (const ep of options.webhookEndpoints) {
      const epClassName = toPascalCase(ep.path) + "Endpoint";
      imports.push(`import { ${epClassName} } from './endpoints/${ep.path}';`);
      extendConfigLines.push(
        `        await configuration.api.provideApi({`,
        `            visibility: ApiVisibility.PUBLIC,`,
        `            security: ApiSecurity.UNSECURE,`,
        `            endpoints: [new ${epClassName}(this)],`,
        `        });`,
      );
    }
  }

  const ACCESSOR_TYPES = new Set([
    "IRead",
    "IHttp",
    "IModify",
    "IPersistence",
    "IEnvironmentRead",
    "IConfigurationExtend",
    "IConfigurationModify",
  ]);
  const accessorTypesNeeded = new Set<string>();

  for (const cap of capabilities) {
    const handlerName = cap.interfaceName.replace(/^I/, "") + "Handler";
    const handlerFile = `./handlers/${handlerName}`;

    imports.push(
      `import { ${cap.interfaceName} } from '@rocket.chat/apps-engine/${cap.importPath}';`,
    );
    imports.push(`import { ${handlerName} } from '${handlerFile}';`);

    implementsList.push(cap.interfaceName);

    for (const method of cap.methods) {
      if (method.isOptional) continue;

      const params = method.parameters.map((p) => {
        if (ACCESSOR_TYPES.has(p.type)) {
          accessorTypesNeeded.add(p.type);
        }
        return `${p.name}${p.isOptional ? "?" : ""}: ${p.type}`;
      });

      const capDir = cap.importPath.split("/").slice(0, -1).join("/");
      for (const p of method.parameters) {
        if (accessorTypesNeeded.has(p.type)) {
          continue;
        }
        imports.push(
          `import type { ${p.type} } from '@rocket.chat/apps-engine/${capDir}';`,
        );
      }

      const ctorArgs = method.parameters.map((p) => p.name).join(", ");

      methodBlocks.push(`
    public async ${method.name}(
        ${params.join(",\n        ")},
    ): ${method.returnType} {
        const handler = new ${handlerName}(this, ${ctorArgs});
        await handler.run();
    }`);
    }
  }

  if (options.bridged) {
    methodBlocks.push(`
    public async onEnable(): Promise<boolean> {
        const logger = this.getLogger();
        try {
            const url = await this.getAccessors().environmentReader
                .getSettings().getValueById('mcp_server_url');
            if (url) {
                logger.info(\`[MCP] App enabled. MCP Server URL: \${url}\`);
                if (url.includes('localhost') || url.includes('127.0.0.1')) {
                    logger.warn('[MCP] URL points to localhost. If Rocket.Chat runs in Docker/K8s, use http://host.docker.internal:PORT or the host machine IP instead.');
                }
            } else {
                logger.warn('[MCP] mcp_server_url is not set. Configure it in Admin → Apps → Settings.');
            }
        } catch {
            // Settings may not be fully initialized yet
        }
        return true;
    }`);
  }

  if (accessorTypesNeeded.size > 0) {
    imports.push(
      `import { ${[...accessorTypesNeeded].sort().join(", ")} } from '@rocket.chat/apps-engine/definition/accessors';`,
    );
  }

  const implementsStr =
    implementsList.length > 0 ? ` implements ${implementsList.join(", ")}` : "";

  const uniqueImports = [...new Set(imports)];

  return `/**
 * ${options.appName} — Rocket.Chat App
 * ${esc(options.description)}
 *
 * Event interfaces: ${implementsList.join(", ") || "none"}
 * Dynamically generated from @rocket.chat/apps-engine definitions.
 *
 * Generated by rc-mcp-generator (RC App mode — dynamic)
 * Deploy: rc-apps deploy --url <server_url> -u <user> -p <password>
 */

${uniqueImports.join("\n")}

export class ${className} extends App${implementsStr} {
    constructor(info: IAppInfo, logger: ILogger, accessors: IAppAccessors) {
        super(info, logger, accessors);
        logger.debug('${esc(options.appName)} initialized');
    }

    public async extendConfiguration(configuration: IConfigurationExtend): Promise<void> {
${extendConfigLines.join("\n")}
    }
${methodBlocks.join("\n")}
}
`;
}

function addImport(
  map: Map<string, Set<string>>,
  path: string,
  type: string,
): void {
  let types = map.get(path);
  if (!types) {
    types = new Set();
    map.set(path, types);
  }
  types.add(type);
}

export function generateMessageHelperCode(): string {
  return `/**
 * Message helpers — reusable functions for creating and sending messages.
 *
 * Pattern follows Apps.Rasa (createMessage) and Apps.Chat.Summarize (notifyMessage).
 *
 * Generated by rc-mcp-generator (RC App mode)
 */

import { IModify, IRead } from '@rocket.chat/apps-engine/definition/accessors';
import { IRoom } from '@rocket.chat/apps-engine/definition/rooms';
import { IUser } from '@rocket.chat/apps-engine/definition/users';

/**
 * Send a message to a room (visible to everyone).
 */
export async function sendMessage(
    read: IRead,
    modify: IModify,
    room: IRoom,
    text: string,
    threadId?: string,
): Promise<string> {
    const appUser = await read.getUserReader().getAppUser();
    if (!appUser) {
        throw new Error('App user not found');
    }

    const msg = modify.getCreator().startMessage()
        .setSender(appUser)
        .setRoom(room)
        .setText(text);

    if (threadId) {
        msg.setThreadId(threadId);
    }

    return modify.getCreator().finish(msg);
}

/**
 * Send a notification only visible to a specific user.
 * Useful for ephemeral responses to slash commands.
 */
export async function notifyUser(
    read: IRead,
    modify: IModify,
    room: IRoom,
    user: IUser,
    text: string,
    threadId?: string,
): Promise<void> {
    const appUser = await read.getUserReader().getAppUser();
    if (!appUser) {
        throw new Error('App user not found');
    }

    const msg = modify.getCreator().startMessage()
        .setSender(appUser)
        .setRoom(room)
        .setText(text);

    if (threadId) {
        msg.setThreadId(threadId);
    }

    await modify.getNotifier().notifyUser(user, msg.getMessage());
}
`;
}

export function generateAppSettingsCode(options: AppGenOptions): string {
  const settingsEntries: string[] = [];

  settingsEntries.push(`    {
        id: 'target_channel',
        type: SettingType.STRING,
        packageValue: '',
        required: false,
        public: false,
        i18nLabel: 'Target Channel',
        i18nDescription: 'Only respond in this channel (leave empty for all channels)',
    }`);

  if (options.messageHandlers) {
    settingsEntries.push(`    {
        id: 'bot_username',
        type: SettingType.STRING,
        packageValue: '${toCamelCase(options.appName)}-bot',
        required: false,
        public: false,
        i18nLabel: 'Bot Username',
        i18nDescription: 'Username of the bot account used by this app',
    }`);

    settingsEntries.push(`    {
        id: 'llm_api_url',
        type: SettingType.STRING,
        packageValue: '',
        required: false,
        public: false,
        i18nLabel: 'LLM API URL',
        i18nDescription: 'Optional: URL of an LLM API endpoint for smart message matching (e.g. http://localhost:11434/v1/chat/completions)',
    }`);

    settingsEntries.push(`    {
        id: 'service_unavailable_message',
        type: SettingType.STRING,
        packageValue: 'Sorry, I am unable to process your request at the moment.',
        required: false,
        public: false,
        i18nLabel: 'Service Unavailable Message',
        i18nDescription: 'Message to send when the app encounters an error',
    }`);
  }

  if (options.bridged) {
    settingsEntries.push(`    {
        id: 'mcp_server_url',
        type: SettingType.STRING,
        packageValue: 'http://localhost:3001',
        required: true,
        public: false,
        i18nLabel: 'MCP Server URL',
        i18nDescription: 'URL of the MCP Server HTTP bridge. Default http://localhost:3001 works when both run on the same host. If RC is in Docker, use http://host.docker.internal:3001 to reach the host machine.',
    }`);

    settingsEntries.push(`    {
        id: 'bot_username',
        type: SettingType.STRING,
        packageValue: '',
        required: false,
        public: false,
        i18nLabel: 'Bot Username',
        i18nDescription: 'Username of the RC account used by the MCP server (from .env ROCKETCHAT_USER). Messages from this user are ignored to prevent feedback loops.',
    }`);
  }

  return `/**
 * App Settings — configurable values accessible from the RC admin panel.
 *
 * Pattern follows Apps.Rasa / Apps.Dialogflow:
 * - Define settings as ISetting[] array
 * - Register in extendConfiguration()
 * - Read at runtime via read.getEnvironmentReader().getSettings().getValueById()
 *
 * Generated by rc-mcp-generator (RC App mode)
 */

import { ISetting, SettingType } from '@rocket.chat/apps-engine/definition/settings';

export const settings: Array<ISetting> = [
${settingsEntries.join(",\n")}
];
`;
}

export function generateGitIgnoreCode(): string {
  return `# ignore modules pulled in from npm
node_modules/

# rc-apps package output
dist/

# JetBrains IDEs
out/
.idea/
.idea_modules/

# macOS
.DS_Store

# Environment
.env
.env.local
`;
}

export function generateEditorConfigCode(): string {
  return `# EditorConfig — https://EditorConfig.org

root = true

[*]
indent_style = space
indent_size = 4
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
`;
}

export function generateRcAppsConfigCode(): string {
  return (
    JSON.stringify(
      {
        url: "http://localhost:3000",
        username: "admin",
        password: "admin",
      },
      null,
      2,
    ) + "\n"
  );
}

export function generateRcAppPackageJsonCode(appName: string): string {
  return JSON.stringify(
    {
      devDependencies: {
        "@rocket.chat/apps-engine": "^1.44.0",
        "@types/node": "14.14.6",
        typescript: "^5.6.2",
      },
      dependencies: {
        "@rocket.chat/ui-kit": "^0.36.1",
      },
      scripts: {
        build: "npx tsc",
        deploy: "rc-apps deploy",
        "deploy:local":
          "rc-apps deploy --url http://localhost:3000 --username admin --password admin",
        watch: "rc-apps watch",
      },
    },
    null,
    2,
  );
}

export function generateRcAppTsConfigCode(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "es2017",
        module: "commonjs",
        lib: ["es2017"],
        declaration: true,
        strict: true,
        noImplicitAny: false,
        strictNullChecks: true,
        noImplicitThis: true,
        noUnusedLocals: false,
        noUnusedParameters: false,
        moduleResolution: "node",
        esModuleInterop: true,
        outDir: "./dist",
        rootDir: ".",
      },
      include: ["./**/*.ts"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2,
  );
}

export function generateRcAppReadmeCode(options: AppGenOptions): string {
  const commandList =
    options.commands.length > 0
      ? options.commands
          .map((c) => `- \`/${c.command}\` — ${c.description}`)
          .join("\n")
      : "No slash commands configured.";

  const webhookList =
    options.webhookEndpoints.length > 0
      ? options.webhookEndpoints
          .map(
            (e) =>
              `- \`${e.methods.map((m) => m.toUpperCase()).join("/")} /${e.path}\` — ${e.description}`,
          )
          .join("\n")
      : "No webhook endpoints configured.";

  const features: string[] = [];
  if (options.commands.length > 0)
    features.push(`${options.commands.length} slash commands`);
  if (options.messageHandlers) features.push("message event handlers");
  if (options.webhookEndpoints.length > 0)
    features.push(`${options.webhookEndpoints.length} webhook endpoints`);
  if (options.workflows.length > 0)
    features.push(`${options.workflows.length} embedded workflows`);

  return `# ${options.appName}

${options.description}

**Generated by rc-mcp-generator (RC App mode)**

## Features

${features.map((f) => `- ${f}`).join("\n")}

## Slash Commands

${commandList}

## Webhook Endpoints

${webhookList}

${options.messageHandlers ? "## Event Handlers\n\n- **IPostMessageSent** — Reacts to every message sent in rooms the app has access to\n" : ""}

## Setup

### Prerequisites

- Node.js 18+
- [RC Apps CLI](https://github.com/RocketChat/Rocket.Chat.Apps-cli): \`npm install -g @rocket.chat/apps-cli\`
- A running Rocket.Chat server (development mode enabled)

### Install & Deploy

\`\`\`bash
npm install
rc-apps deploy --url http://localhost:3000 -u admin -p admin
\`\`\`

### Development

\`\`\`bash
# Watch mode — auto-redeploy on changes
rc-apps watch --url http://localhost:3000 -u admin -p admin
\`\`\`

## Architecture

This app runs inside Rocket.Chat's Apps-Engine, a sandboxed TypeScript runtime.
Unlike external MCP servers that communicate via stdio, this app has direct access
to Rocket.Chat internals through the Apps-Engine accessors (\`IRead\`, \`IModify\`,
\`IHttp\`, \`IPersistence\`).

### MCP Server vs RC App

| Aspect | MCP Server | RC App (this) |
|--------|-----------|---------------|
| Runs | External process | Inside RC server |
| Trigger | LLM tool call | Messages, commands, webhooks, schedules |
| RC access | REST API (HTTP) | Direct accessors (IRead, IModify) |
| Deploy | \`node server.js\` | \`rc-apps deploy\` |
| Realtime | No (request/response) | Yes (event interfaces) |
`;
}

export function generatePlaceholderIconBuffer(): Buffer {
  return Buffer.from(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==",
    "base64",
  );
}

export function generateMcpBridgeCode(appName: string): string {
  return `/**
 * MCP Bridge — connects the RC App to an external MCP Server.
 *
 * The RC App catches events (messages, room creation, etc.) but cannot
 * invoke LLMs directly (no ILlm accessor in Apps-Engine). This bridge
 * delegates AI reasoning to the MCP Server, which has sampling capabilities.
 *
 * Architecture (Bridged):
 *   RC Event → RC App (IPostMessageSent) → McpBridge.callTool() → MCP Server
 *   MCP Server runs workflow (api_call + sampling) → returns result
 *   RC App posts result back to Rocket.Chat channel
 *
 * Generated by rc-mcp-generator (bridged mode)
 */

import { IHttp } from '@rocket.chat/apps-engine/definition/accessors';
import { IRead } from '@rocket.chat/apps-engine/definition/accessors';

export interface DeferredAction {
    stepId: string;
    operationId: string;
    method: string;
    path: string;
    payload: Record<string, unknown>;
}

export interface McpToolResult {
    status: 'success' | 'error';
    content: string;
    completedSteps?: string[];
    deferredActions?: DeferredAction[];
}

export class McpBridge {
    constructor(
        private readonly http: IHttp,
        private readonly read: IRead,
    ) {}

    /**
     * Get the MCP Server URL from app settings.
     * Defaults to localhost:3001 for development.
     */
    private async getMcpUrl(): Promise<string> {
        const url = await this.read.getEnvironmentReader()
            .getSettings().getValueById('mcp_server_url');
        return url || 'http://localhost:3001';
    }

    /**
     * Call an MCP tool on the external server.
     * Uses JSON-RPC format matching the MCP protocol.
     */
    public async callTool(
        toolName: string,
        args: Record<string, unknown>,
    ): Promise<McpToolResult> {
        const mcpUrl = await this.getMcpUrl();

        try {
            const response = await this.http.post(
                \`\${mcpUrl}/mcp\`,
                {
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    content: JSON.stringify({
                        jsonrpc: '2.0',
                        id: Date.now(),
                        method: 'tools/call',
                        params: {
                            name: toolName,
                            arguments: args,
                        },
                    }),
                },
            );

            if (!response || !response.content) {
                return {
                    status: 'error',
                    content: 'No response from MCP server',
                };
            }

            const result = JSON.parse(response.content);

            if (result.error) {
                return {
                    status: 'error',
                    content: result.error.message || 'MCP tool call failed',
                };
            }

            // Extract text content from MCP response
            const textContent = result.result?.content
                ?.filter((c: any) => c.type === 'text')
                ?.map((c: any) => c.text)
                ?.join('\\n') ?? '';

            // Try to parse as JSON to extract structured data
            try {
                const parsed = JSON.parse(textContent);
                return {
                    status: parsed.status || 'success',
                    content: parsed.error
                        ? \`Error: \${parsed.error}\\nCompleted: \${(parsed.completedSteps || []).join(' → ')}\\nResults: \${JSON.stringify(parsed.stepResults, null, 2)}\`
                        : parsed.stepResults
                            ? JSON.stringify(parsed.stepResults, null, 2)
                            : textContent,
                    completedSteps: parsed.completedSteps,
                    deferredActions: parsed.deferredActions,
                };
            } catch {
                return {
                    status: 'success',
                    content: textContent,
                };
            }
        } catch (error) {
            return {
                status: 'error',
                content: \`MCP bridge error (url: \${mcpUrl}): \${error instanceof Error ? error.message : String(error)}\`,
            };
        }
    }

    /**
     * List available tools on the MCP server.
     */
    public async listTools(): Promise<string[]> {
        const mcpUrl = await this.getMcpUrl();

        try {
            const response = await this.http.post(
                \`\${mcpUrl}/mcp\`,
                {
                    headers: { 'Content-Type': 'application/json' },
                    content: JSON.stringify({
                        jsonrpc: '2.0',
                        id: Date.now(),
                        method: 'tools/list',
                        params: {},
                    }),
                },
            );

            if (!response?.content) return [];
            const result = JSON.parse(response.content);
            return (result.result?.tools || []).map((t: any) => t.name);
        } catch {
            return [];
        }
    }
}
`;
}

export function generateBridgedEventHandlerCode(
  capability: AppCapability,
  appName: string,
  workflowToolName: string,
  persistenceConfig?: PersistenceConfig,
): string {
  const handlerName = capability.interfaceName.replace(/^I/, "") + "Handler";

  const executeMethod =
    capability.methods.find((m) => !m.isOptional) ?? capability.methods[0];

  const ACCESSOR_TYPES = new Set([
    "IRead",
    "IHttp",
    "IModify",
    "IPersistence",
    "IEnvironmentRead",
    "IConfigurationExtend",
    "IConfigurationModify",
  ]);
  const accessorTypes = new Set<string>();
  const domainImports = new Map<string, Set<string>>();

  const capDir = capability.importPath.split("/").slice(0, -1).join("/");
  const capImportBase = `@rocket.chat/apps-engine/${capDir}`;

  for (const param of executeMethod.parameters) {
    if (ACCESSOR_TYPES.has(param.type)) {
      accessorTypes.add(param.type);
    } else {
      addImport(domainImports, capImportBase, param.type);
    }
  }

  accessorTypes.add("IHttp");
  accessorTypes.add("IRead");
  accessorTypes.add("IModify");

  if (persistenceConfig) {
    accessorTypes.add("IPersistence");
  }

  const imports: string[] = [];
  if (accessorTypes.size > 0) {
    imports.push(
      `import { ${[...accessorTypes].sort().join(", ")} } from '@rocket.chat/apps-engine/definition/accessors';`,
    );
  }
  imports.push(
    `import { IApp } from '@rocket.chat/apps-engine/definition/IApp';`,
  );
  imports.push(`import { McpBridge } from '../bridge/mcp-bridge';`);

  if (persistenceConfig) {
    imports.push(
      `import { RocketChatAssociationModel, RocketChatAssociationRecord } from '@rocket.chat/apps-engine/definition/metadata';`,
    );
  }

  for (const [path, types] of domainImports) {
    imports.push(`import { ${[...types].sort().join(", ")} } from '${path}';`);
  }

  const ctorParams = executeMethod.parameters.map((p) => {
    return `        private readonly ${p.name}: ${p.type},`;
  });

  const domainParam = executeMethod.parameters.find(
    (p) => !ACCESSOR_TYPES.has(p.type),
  );

  const handlerBody = generateBridgedBody(
    workflowToolName,
    capability.category,
    domainParam ?? null,
    persistenceConfig,
  );

  const lines = [
    `/**`,
    ` * ${handlerName} — Bridged handler for ${capability.interfaceName}.`,
    ` *`,
    ` * This handler delegates AI reasoning to an external MCP Server.`,
    ` * The RC App catches the event, the MCP Server processes it with`,
    ` * sampling (LLM reasoning), and the result is posted back.`,
    ` *`,
    ` * Architecture: RC Event → This Handler → McpBridge → MCP Server → AI → RC`,
    ` *`,
    ` * Generated by rc-mcp-generator (bridged mode)`,
    ` */`,
    ``,
    imports.join("\n"),
    ``,
    `export class ${handlerName} {`,
    `    constructor(`,
    `        private readonly app: IApp,`,
    ctorParams.join("\n"),
    `    ) {}`,
    ``,
    `    public async run(): Promise<void> {`,
    `        const logger = this.app.getLogger();`,
    ``,
    handlerBody,
    `    }`,
    `}`,
    ``,
  ];

  return lines.join("\n");
}

function generateBridgedBody(
  toolName: string,
  category: string,
  domainParam: { name: string; type: string } | null,
  persistenceConfig?: PersistenceConfig,
): string {
  const paramRef = domainParam ? `this.${domainParam.name}` : "null";
  const paramType = domainParam?.type ?? "";
  const isContext = paramType.includes("Context");

  let roomExpr: string | null = null;
  let userExpr: string | null = null;
  let extractLines: string[] = [];

  if (category === "messages") {
    extractLines = [
      `        // 1. Extract message context`,
      `        const { text, room, sender } = ${paramRef};`,
      ``,
      `        // Ignore bot messages (prevents infinite loops)`,
      `        if (sender.roles?.includes('bot')) return;`,
      ``,
      `        const appUser = await this.read.getUserReader().getAppUser();`,
      `        if (appUser && sender.id === appUser.id) return;`,
      ``,
      `        // Ignore messages from the MCP server's RC user (prevents feedback loops)`,
      `        const botUsername = await this.read.getEnvironmentReader()`,
      `            .getSettings().getValueById('bot_username');`,
      `        if (botUsername && sender.username === botUsername) return;`,
      ``,
      `        // Skip non-text messages (file uploads, reactions, etc.)`,
      `        if (!text) return;`,
      ``,
      "        logger.info(`[Bridge] Message from ${sender.username} in #${room.slugifiedName}: ${text}`);",
    ];
    roomExpr = "room";
    userExpr = "sender";
  } else if (isContext) {
    const contextFields = deriveContextFields(paramType);
    extractLines = [`        // 1. Extract event context`];
    if (contextFields.room) {
      extractLines.push(
        `        const room = ${paramRef}.${contextFields.room};`,
      );
      roomExpr = "room";
    }
    if (contextFields.user) {
      extractLines.push(
        `        const user = ${paramRef}.${contextFields.user};`,
      );
      userExpr = "user";
    }
    if (roomExpr) {
      extractLines.push(
        "        logger.info(`[Bridge] ${'" +
          category +
          "' } event in #${room.slugifiedName}`);",
      );
    } else {
      extractLines.push(
        `        logger.info('[Bridge] ${category} event received');`,
      );
    }
  } else if (paramType === "IRoom") {
    extractLines = [
      `        // 1. Extract room context`,
      `        const room = ${paramRef};`,
      "        logger.info(`[Bridge] " +
        (category === "livechat" ? "Livechat" : "Room") +
        " event: #${room.slugifiedName} (type: ${room.type})`);",
    ];
    roomExpr = "room";
  } else {
    extractLines = [
      `        // 1. Event received`,
      `        logger.info('[Bridge] ${category} event received');`,
    ];
  }

  if (category === "users" && domainParam) {
    extractLines.push(
      ``,
      `        // Skip bot and app users — no onboarding needed`,
      `        const eventUser = ${paramRef}?.user;`,
      `        if (eventUser?.type === 'bot' || eventUser?.type === 'app' || eventUser?.roles?.includes('bot') || eventUser?.roles?.includes('app')) {`,
      `            logger.debug('[Bridge] Skipping bot/app user: ' + (eventUser?.username || 'unknown'));`,
      `            return;`,
      `        }`,
    );
  }

  const lines = [...extractLines, ``];

  if (persistenceConfig) {
    const modelLiteral = {
      user: "RocketChatAssociationModel.USER",
      room: "RocketChatAssociationModel.ROOM",
      misc: "RocketChatAssociationModel.MISC",
    }[persistenceConfig.model];
    const keyAccess = (() => {
      let kp = persistenceConfig.keyPath;
      if (domainParam && kp.startsWith(domainParam.name + ".")) {
        kp = kp.slice(domainParam.name.length + 1);
      }
      return `${paramRef}.${kp}`;
    })();
    const defaultJson = JSON.stringify(persistenceConfig.defaultState);

    lines.push(
      `        // 2. Read persisted state`,
      `        const persistKey = ${keyAccess};`,
      `        const assoc = new RocketChatAssociationRecord(`,
      `            ${modelLiteral},`,
      `            String(persistKey),`,
      `        );`,
      `        const records = await this.read.getPersistenceReader().readByAssociation(assoc);`,
      `        const ${persistenceConfig.stateParam} = records.length > 0`,
      `            ? (records[0] as Record<string, unknown>)`,
      `            : ${defaultJson};`,
      ``,
      `        // 3. Delegate to MCP Server with persisted state`,
      `        const bridge = new McpBridge(this.http, this.read);`,
      `        const result = await bridge.callTool('${esc(toolName)}',`,
    );
    if (domainParam) {
      lines.push(
        `            { ${domainParam.name}: ${paramRef}, ${persistenceConfig.stateParam} },`,
      );
    } else {
      lines.push(
        `            { eventType: '${esc(category)}', ${persistenceConfig.stateParam} },`,
      );
    }
    lines.push(`        );`, ``);
  } else {
    lines.push(
      `        // 2. Delegate to MCP Server for AI reasoning`,
      `        const bridge = new McpBridge(this.http, this.read);`,
      `        const result = await bridge.callTool('${esc(toolName)}',`,
    );
    if (domainParam) {
      lines.push(`            { ${domainParam.name}: ${paramRef} },`);
    } else {
      lines.push(`            { eventType: '${esc(category)}' },`);
    }
    lines.push(`        );`, ``);
  }

  const logStepNum = persistenceConfig ? "4" : "3";
  const nextStepNum = parseInt(logStepNum) + 1;

  lines.push(
    `        // ${logStepNum}. Log workflow result`,
    `        if (result.status === 'success') {`,
    `            logger.info('[Bridge] Workflow completed:', result.completedSteps);`,
    `        } else if (result.status === 'error') {`,
    `            logger.error('[Bridge] MCP Server error:', result.content);`,
    `        }`,
  );

  if (persistenceConfig?.updateFromStep) {
    const stepId = persistenceConfig.updateFromStep;
    lines.push(
      ``,
      `        // ${nextStepNum}. Update persisted state from workflow result`,
      `        if (result.status === 'success' && result.content) {`,
      `            try {`,
      `                const stepResults = JSON.parse(result.content);`,
      `                const stepEntry = stepResults[${JSON.stringify(stepId)}];`,
      `                if (stepEntry?.status === 'success' && stepEntry.result !== undefined) {`,
      `                    const updatedState = stepEntry.result;`,
      `                    if (records.length > 0) {`,
      `                        await this.persistence.updateByAssociation(assoc, updatedState);`,
      `                    } else {`,
      `                        await this.persistence.createWithAssociation(updatedState, assoc);`,
      `                    }`,
      `                    logger.info('[Bridge] Persisted state updated from step "${stepId}"');`,
      `                }`,
      `            } catch (e) {`,
      `                logger.error('[Bridge] Failed to update persisted state:', e);`,
      `            }`,
      `        }`,
    );
  }

  return lines.join("\n");
}

function deriveContextFields(typeName: string): {
  room: string | null;
  user: string | null;
} {
  const lower = typeName.toLowerCase();
  if (lower.includes("userjoined"))
    return { room: "room", user: "joiningUser" };
  if (lower.includes("userleave")) return { room: "room", user: "leavingUser" };
  if (lower.includes("livechat")) return { room: "room", user: null };
  if (lower.includes("room")) return { room: "room", user: null };
  return { room: null, user: null };
}

